Fix: Correct method name for comment captcha validation
Fixed fatal error when submitting WordPress comments. The hook was calling
non-existent method 'woo_check_comment_captcha' which should be
'woo_verify_comment_captcha'.

Error: call_user_func_array(): Argument #1 must be a valid callback,
class Woocommerce_Filter does not have a method woo_check_comment_captcha

Fixed by changing method name in hook registration:
- Old: add_filter('preprocess_comment', [...], 'woo_check_comment_captcha')
- New: add_filter('preprocess_comment', [...], 'woo_verify_comment_captcha')

File: includes/class-recaptcha-for-buddypress.php:350
Fixes: #9226573777